include:
  - /.gitlab/k8s.yml
#  - /.gitlab/ansible.yml

stages:
  - prebuild
  - build
  - test
  - sast
  - release
  - deploy
  - dast
  - setup

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

.dependencies_cache:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm
    policy: pull
